const { Employee } = require("../models");

const populateEmployee = async () => {
  const employees = [
    {
      emp_fname: "April Joy",
      emp_lname: "Adi",
      emp_mname: "Advincula",
      emp_suffix: null,
      emp_dob: "2000-04-13",
      emp_gender: "Female",
      emp_email: "adijoyworks@gmail.com",
      emp_contact: "+639389040578",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 1,
      position_id: 1,
      emp_status_id: 1,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Danreiner",
      emp_lname: "Buenconsejo",
      emp_mname: "Robes",
      emp_suffix: null,
      emp_dob: "1999-11-25",
      emp_gender: "Male",
      emp_email: "daneriner@gmail.com",
      emp_contact: "+639389040578",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 2,
      position_id: 2,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Trisha",
      emp_lname: "Adi",
      emp_mname: "Advincula",
      emp_suffix: null,
      emp_dob: "2010-05-22",
      emp_gender: "Female",
      emp_email: "trsihaAdi@gmail.com",
      emp_contact: "+639359140126",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 3,
      position_id: 2,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Shane",
      emp_lname: "Adi",
      emp_mname: "Advincula",
      emp_suffix: null,
      emp_dob: "2010-05-22",
      emp_gender: "Female",
      emp_email: "shaneAdi@gmail.com",
      emp_contact: "+639359140126",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 2,
      position_id: 4,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Jonalyn",
      emp_lname: "Adi",
      emp_mname: "Advincula",
      emp_suffix: null,
      emp_dob: "1988-03-31",
      emp_gender: "Female",
      emp_email: "jonaAdi@gmail.com",
      emp_contact: "+639359140126",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 4,
      position_id: 3,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Dante",
      emp_lname: "Buenconsejo",
      emp_mname: "Kila",
      emp_suffix: "Jr.",
      emp_dob: "1991-04-13",
      emp_gender: "Male",
      emp_email: "dantebuen@gmail.com",
      emp_contact: "+639359015574",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 1,
      position_id: 1,
      emp_status_id: 1,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Carolyn",
      emp_lname: "Advincula",
      emp_mname: "Devilla",
      emp_suffix: null,
      emp_dob: "1969-02-26",
      emp_gender: "Female",
      emp_email: "carolyn@gmail.com",
      emp_contact: "+639504004027",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 2,
      position_id: 2,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Christian",
      emp_lname: "Ronles",
      emp_mname: "Makara",
      emp_suffix: null,
      emp_dob: "1990-01-12",
      emp_gender: "Male",
      emp_email: "christianmakara@gmail.com",
      emp_contact: "+639126544478",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 3,
      position_id: 2,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Jojo",
      emp_lname: "Adi",
      emp_mname: "Terazola",
      emp_suffix: null,
      emp_dob: "1967-05-01",
      emp_gender: "Male",
      emp_email: "jojoadi@gmail.com",
      emp_contact: "+639275440155",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 2,
      position_id: 4,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
    {
      emp_fname: "Vico",
      emp_lname: "Moreno",
      emp_mname: "Sinda",
      emp_suffix: "Sr.",
      emp_dob: "1988-03-31",
      emp_gender: "Male",
      emp_email: "vicomeron@gmail.com",
      emp_contact: "+639502015544",
      nationality_id: 1,
      civil_status_id: 1,
      dept_id: 4,
      position_id: 3,
      emp_status_id: 2,
      date_hire: "2020-01-13",
    },
  ];

  for (const employee of employees) {
    await Employee.findOrCreate({
      where: {
        emp_fname: employee.emp_fname,
        emp_lname: employee.emp_lname,
        emp_mname: employee.emp_mname,
        emp_suffix: employee.emp_suffix,
        emp_dob: employee.emp_dob,
        emp_gender: employee.emp_gender,
        emp_email: employee.emp_email,
        emp_contact: employee.emp_contact,
        nationality_id: employee.nationality_id,
        civil_status_id: employee.civil_status_id,
        dept_id: employee.dept_id,
        position_id: employee.position_id,
        emp_status_id: employee.emp_status_id,
        date_hire: employee.date_hire,
      },
      defaults: employee,
    });
  }

  console.log("Database populated with employees.");
};

module.exports = populateEmployee;
